### ISSUE TITLE
Can't build as Monoid.v is missing

### ISSUE THREAD

**Issue by k4rtik** [inQWIRE/QWIRE#1]
Commit https://github.com/jpaykin/QWIRE/commit/b622027aa26046b240122d095bf827152a32e414 introduced a dependency on `Monoid.v` but the file is missing in the repository since it was removed with commit 192718f6a6fc45286fb780874d323de9024062c9

```
$ make clean && make -j8
rm *.vo
coqc Monad.v
make: *** No rule to make target 'Monoid.v', needed by 'Monoid.vo'.  Stop.

```

**Comment by rnrand** [comment]
Whoops! It's actually a new version of monoid, adapted from https://github.com/jpaykin/LinearTypingContexts, that I apparently forgot to 'add'.

Should be fixed now!

**Comment by k4rtik** [comment]
@rnrand sorry, I don't see the file in the latest commit.

**Comment by k4rtik** [comment]
If I just copy the file over from jpaykin/LinearTypingContexts, I see the following error on `make all -j8`:
```
coqc Contexts.v 
File "./Contexts.v", line 2, characters 0-22:
Error:
Level 20 is already declared right associative while it is now expected to be left associative.

make: *** [Makefile:24: Contexts.vo] Error 1
make: *** Waiting for unfinished jobs....
```

Coq version info:
```
$ coqc --version
The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 14 2018 7:28:08 with OCaml 4.07.0

```

**Comment by rnrand** [comment]
Yeah, don't do that. It's based on that file, but I did have to make a number of modifications to make it work with QWIRE.

I'm not sure what went wrong before, but I'm seeing it on Github now.

**Comment by k4rtik** [comment]
Thanks, it is building now!

I understand, dealing with git can be crazy sometimes, thanks for swiftly looking into this. :smile:
