### ISSUE TITLE
Can't build Matrix.v in coq-8.11.0

### ISSUE THREAD

**Issue by Suikaba** [inQWIRE/QWIRE#5]
I tried to build SQIR project with coq-8.11.0, but I got an error:
```
File "./Matrix.v", line 1361, characters 21-35:
Error:
In environment
m, n, y : nat
H : y mod S n < S n
L1 : y / S n < S m
Unable to unify "S ?M2647 = 0 -> False" with
 "fst (Nat.divmod y (n + m * S n) 0 (n + m * S n)) = 0".
```

~I understand that SQIR and QWIRE doesn't support coq-8.11.0, but I think if removing L1361, you can compile Matrix.v with coq-8.11.0.~
 https://github.com/inQWIRE/QWIRE/blob/ff05005a0e2b20b824449d268c1f68dfba9e7ac2/Matrix.v#L1361

Update:
This issue is fixed: f9037f478a4ea45c2f14a982cc1d4e8171f1652e

**Comment by k4rtik** [comment]
Looks like this issue is resolved with the commit SHA1 mentioned in the update above.
